// The optional D1 starter integration is unused by the Java-backed application.
// Runtime types are generated by Wrangler in worker-configuration.d.ts.
declare namespace Cloudflare {
  interface Env { DB?: D1Database; }
}
